
import fs from 'fs';

const CACHE_FILE = './translation-cache.json';
const cache = JSON.parse(fs.readFileSync(CACHE_FILE, 'utf-8'));

const translations: Record<string, Record<string, string>> = {
  "es": {
    "Resources": "Recursos",
    "Tips": "Consejos",
    "Get control of your life": "Tome el control de su vida",
    "Quotes": "Frases",
    "One day at a time": "Un día a la vez",
    "Ebooks": "Libros electrónicos",
    "Books are a man's best friend": "Los libros son el mejor amigo del hombre",
    "Exercises": "Ejercicios",
    "Learn": "Aprender",
    "Budgeting": "Presupuesto",
    "Banking": "Banca",
    "Credit History": "Historial de crédito",
    "Debt Reduction": "Reducción de deuda",
    "Saving": "Ahorro",
    "Tax Filing": "Declaración de impuestos",
    "min": "min",
    "sessions": "sesiones",
    "Thank You!": "¡Gracias!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Tu entrada ha sido guardada con éxito. Puedes volver a ver tus respuestas en cualquier momento en la sección de Historial.",
    "Got it": "Entendido"
  },
  "fr": {
    "Resources": "Ressources",
    "Tips": "Conseils",
    "Get control of your life": "Prenez le contrôle de votre vie",
    "Quotes": "Citations",
    "One day at a time": "Un jour à la fois",
    "Ebooks": "E-books",
    "Books are a man's best friend": "Les livres sont les meilleurs amis de l'homme",
    "Exercises": "Exercices",
    "Learn": "Apprendre",
    "Budgeting": "Budgétisation",
    "Banking": "Banque",
    "Credit History": "Historique de crédit",
    "Debt Reduction": "Désendettement",
    "Saving": "Épargne",
    "Tax Filing": "Déclaration d'impôts",
    "min": "min",
    "sessions": "sessions",
    "Thank You!": "Merci !",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Votre entrée a été enregistrée avec succès. Vous pouvez consulter vos réponses à tout moment dans la section Historique.",
    "Got it": "J'ai compris"
  },
  "pt": {
    "Resources": "Recursos",
    "Tips": "Dicas",
    "Get control of your life": "Assuma o controle de sua vida",
    "Quotes": "Citações",
    "One day at a time": "Um dia de cada vez",
    "Ebooks": "E-books",
    "Books are a man's best friend": "Os livros são os melhores amigos do homem",
    "Exercises": "Exercícios",
    "Learn": "Aprender",
    "Budgeting": "Orçamento",
    "Banking": "Serviços Bancários",
    "Credit History": "Histórico de Crédito",
    "Debt Reduction": "Redução de Dívida",
    "Saving": "Poupança",
    "Tax Filing": "Declaração de Impostos",
    "min": "min",
    "sessions": "sessões",
    "Thank You!": "Obrigada!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Sua resposta foi salva com sucesso. Você pode revisitar suas respostas a qualquer momento na seção Histórico.",
    "Got it": "Entendi"
  },
  "de": {
    "Resources": "Ressourcen",
    "Tips": "Tipps",
    "Get control of your life": "Übernimm die Kontrolle über dein Leben",
    "Quotes": "Zitate",
    "One day at a time": "Einen Tag nach dem anderen",
    "Ebooks": "E-Books",
    "Books are a man's best friend": "Bücher sind der beste Freund des Menschen",
    "Exercises": "Übungen",
    "Learn": "Lernen",
    "Budgeting": "Budgetierung",
    "Banking": "Bankwesen",
    "Credit History": "Kredithistorie",
    "Debt Reduction": "Schuldenabbau",
    "Saving": "Sparen",
    "Tax Filing": "Steuererklärung",
    "min": "Min.",
    "sessions": "Sitzungen",
    "Thank You!": "Vielen Dank!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Dein Eintrag wurde erfolgreich gespeichert. Du kannst deine Antworten jederzeit im Bereich „Verlauf“ einsehen.",
    "Got it": "Verstanden"
  },
  "ar": {
    "Resources": "موارد",
    "Tips": "نصائح",
    "Get control of your life": "سيطر على حياتك",
    "Quotes": "اقتباسات",
    "One day at a time": "يوماً بيوم",
    "Ebooks": "كتب إلكترونية",
    "Books are a man's best friend": "الكتب هي أفضل صديق للإنسان",
    "Exercises": "تمارين",
    "Learn": "تعلّم",
    "Budgeting": "الميزانية",
    "Banking": "العمليات المصرفية",
    "Credit History": "التاريخ الائتماني",
    "Debt Reduction": "تخفيض الديون",
    "Saving": "الادخار",
    "Tax Filing": "تعبئة الضرائب",
    "min": "دقيقة",
    "sessions": "جلسات",
    "Thank You!": "شكراً لك!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "تم حفظ مدخلك بنجاح. يمكنك مراجعة استجاباتك في أي وقت في قسم السجل.",
    "Got it": "فهمت"
  },
  "hi": {
    "Resources": "संसाधन",
    "Tips": "सुझाव",
    "Get control of your life": "अपने जीवन पर नियंत्रण प्राप्त करें",
    "Quotes": "अनमोल वचन",
    "One day at a time": "एक बार में एक दिन",
    "Ebooks": "ई-बुक्स",
    "Books are a man's best friend": "पुस्तकें मनुष्य की सबसे अच्छी मित्र होती हैं",
    "Exercises": "व्यायाम",
    "Learn": "सीखें",
    "Budgeting": "बजट बनाना",
    "Banking": "बैंकिंग",
    "Credit History": "क्रेडिट इतिहास",
    "Debt Reduction": "ऋण कम करना",
    "Saving": "बचत",
    "Tax Filing": "टैक्स फाइलिंग",
    "min": "मिनट",
    "sessions": "सत्र",
    "Thank You!": "धन्यवाद!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "आपकी प्रविष्टि सफलतापूर्वक सहेज ली गई है। आप इतिहास अनुभाग में किसी भी समय अपनी प्रतिक्रियाएँ देख सकते हैं।",
    "Got it": "समझ गया"
  },
  "tl": {
    "Resources": "Mga Mapagkukunan",
    "Tips": "Mga Tip",
    "Get control of your life": "Kontrolin ang iyong buhay",
    "Quotes": "Mga Quote",
    "One day at a time": "Isang araw sa bawat pagkakataon",
    "Ebooks": "Ebooks",
    "Books are a man's best friend": "Ang mga aklat ay matalik na kaibigan ng tao",
    "Exercises": "Mga Pagsasanay",
    "Learn": "Matuto",
    "Budgeting": "Pagbabadyet",
    "Banking": "Pagbabangko",
    "Credit History": "Kasaysayan ng Credit",
    "Debt Reduction": "Pagbabawas ng Utang",
    "Saving": "Pag-iipon",
    "Tax Filing": "Pag-file ng Buwis",
    "min": "min",
    "sessions": "mga session",
    "Thank You!": "Salamat!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Matagumpay na nai-save ang iyong entry. Maaari mong balikan ang iyong mga tugon anumang oras sa seksyong Kasaysayan.",
    "Got it": "Naintindihan"
  },
  "ur": {
    "Resources": "ذرائع",
    "Tips": "تجاویز",
    "Get control of your life": "اپنی زندگی پر قابو پائیں",
    "Quotes": "اقوال",
    "One day at a time": "ایک وقت میں ایک دن",
    "Ebooks": "ای بکس",
    "Books are a man's best friend": "کتابیں انسان کی بہترین دوست ہوتی ہیں",
    "Exercises": "مشقیں",
    "Learn": "سیکھیں",
    "Budgeting": "بجٹ بنانا",
    "Banking": "بینکاری",
    "Credit History": "کریڈٹ کی تاریخ",
    "Debt Reduction": "قرض میں کمی",
    "Saving": "بچت",
    "Tax Filing": "ٹیکس فائلنگ",
    "min": "منٹ",
    "sessions": "سیشنز",
    "Thank You!": "شکریہ!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "آپ کا اندراج کامیابی کے ساتھ محفوظ ہو گیا ہے۔ آپ ہسٹری سیکشن میں کسی بھی وقت اپنے جوابات دوبارہ دیکھ سکتے ہیں۔",
    "Got it": "سمجھ گیا"
  },
  "bn": {
    "Resources": "সম্পদ",
    "Tips": "পরামর্শ",
    "Get control of your life": "আপনার জীবন নিয়ন্ত্রণে নিন",
    "Quotes": "উদ্ধৃতি",
    "One day at a time": "একবারে একদিন",
    "Ebooks": "ই-বুক",
    "Books are a man's best friend": "বই মানুষের সেরা বন্ধু",
    "Exercises": "ব্যায়াম",
    "Learn": "শিখুন",
    "Budgeting": "বাজেটিং",
    "Banking": "ব্যাংকিং",
    "Credit History": "ক্রেডিট হিস্ট্রি",
    "Debt Reduction": "ঋণ হ্রাস",
    "Saving": "সঞ্চয়",
    "Tax Filing": "ট্যাক্স ফাইলিং",
    "min": "মিনিট",
    "sessions": "সেশন",
    "Thank You!": "ধন্যবাদ!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "আপনার এন্ট্রি সফলভাবে সংরক্ষিত হয়েছে। আপনি যেকোনো সময় হিস্ট্রি বিভাগে গিয়ে আপনার উত্তরগুলো দেখতে পারেন।",
    "Got it": "বুঝেছি"
  },
  "it": {
    "Resources": "Risorse",
    "Tips": "Suggerimenti",
    "Get control of your life": "Prendi il controllo della tua vita",
    "Quotes": "Citazioni",
    "One day at a time": "Un giorno alla volta",
    "Ebooks": "Ebook",
    "Books are a man's best friend": "I libri sono i migliori amici dell'uomo",
    "Exercises": "Esercizi",
    "Learn": "Impara",
    "Budgeting": "Pianificazione",
    "Banking": "Attività Bancaria",
    "Credit History": "Storia Creditizia",
    "Debt Reduction": "Riduzione del Debito",
    "Saving": "Risparmio",
    "Tax Filing": "Dichiarazione dei Redditi",
    "min": "min",
    "sessions": "sessioni",
    "Thank You!": "Grazie!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "La tua voce è stata salvata con successo. Puoi rivedere le tue risposte in qualsiasi momento nella sezione Cronologia.",
    "Got it": "Ricevuto"
  },
  "ru": {
    "Resources": "Ресурсы",
    "Tips": "Советы",
    "Get control of your life": "Возьмите свою жизнь под контроль",
    "Quotes": "Цитаты",
    "One day at a time": "Один день за раз",
    "Ebooks": "Электронные книги",
    "Books are a man's best friend": "Книги — лучшие друзья человека",
    "Exercises": "Упражнения",
    "Learn": "Учить",
    "Budgeting": "Бюджетирование",
    "Banking": "Банковское дело",
    "Credit History": "Кредитная история",
    "Debt Reduction": "Сокращение долга",
    "Saving": "Сбережения",
    "Tax Filing": "Подача налоговой декларации",
    "min": "мин",
    "sessions": "сеансов",
    "Thank You!": "Спасибо!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Ваша запись успешно сохранена. Вы можете просмотреть свои ответы в любое время в разделе «История».",
    "Got it": "Понятно"
  },
  "tr": {
    "Resources": "Kaynaklar",
    "Tips": "İpuçları",
    "Get control of your life": "Hayatınızın kontrolünü elinize alın",
    "Quotes": "Alıntılar",
    "One day at a time": "Her seferinde bir gün",
    "Ebooks": "E-kitaplar",
    "Books are a man's best friend": "Kitaplar insanın en iyi arkadaşıdır",
    "Exercises": "Egzersizler",
    "Learn": "Öğrenmek",
    "Budgeting": "Bütçe yapma",
    "Banking": "Bankacılık",
    "Credit History": "Kredi Geçmişi",
    "Debt Reduction": "Borç Azaltma",
    "Saving": "Tasarruf",
    "Tax Filing": "Vergi Dosyalama",
    "min": "dk",
    "sessions": "oturumlar",
    "Thank You!": "Teşekkürler!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Girişiniz başarıyla kaydedildi. Cevaplarınızı istediğiniz zaman Geçmiş bölümünden tekrar inceleyebilirsiniz.",
    "Got it": "Anladım"
  },
  "vi": {
    "Resources": "Tài nguyên",
    "Tips": "Mẹo",
    "Get control of your life": "Kiểm soát cuộc sống của bạn",
    "Quotes": "Trích dẫn",
    "One day at a time": "Từng ngày một",
    "Ebooks": "Sách điện tử",
    "Books are a man's best friend": "Sách là người bạn tốt nhất của con người",
    "Exercises": "Bài tập",
    "Learn": "Tìm hiểu",
    "Budgeting": "Lập ngân sách",
    "Banking": "Ngân hàng",
    "Credit History": "Lịch sử tín dụng",
    "Debt Reduction": "Giảm nợ",
    "Saving": "Tiết kiệm",
    "Tax Filing": "Kê khai thuế",
    "min": "phút",
    "sessions": "phiên",
    "Thank You!": "Cám ơn!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Mục nhập của bạn đã được lưu thành công. Bạn có thể xem lại phản hồi của mình bất cứ lúc nào trong phần Lịch sử.",
    "Got it": "Đã hiểu"
  },
  "zh": {
    "Resources": "资源",
    "Tips": "提示",
    "Get control of your life": "掌控你的生活",
    "Quotes": "名言",
    "One day at a time": "循序渐进",
    "Ebooks": "电子书",
    "Books are a man's best friend": "书是人类最好的朋友",
    "Exercises": "练习",
    "Learn": "学习",
    "Budgeting": "预算编制",
    "Banking": "银行业务",
    "Credit History": "信用记录",
    "Debt Reduction": "债务减免",
    "Saving": "储蓄",
    "Tax Filing": "报税",
    "min": "分钟",
    "sessions": "场次",
    "Thank You!": "谢谢！",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "您的条目已成功保存。您可以随时在“历史记录”部分重新查看您的回复。",
    "Got it": "明白了"
  },
  "ja": {
    "Resources": "リソース",
    "Tips": "ヒント",
    "Get control of your life": "生活をコントロールする",
    "Quotes": "名言",
    "One day at a time": "一日一歩ずつ",
    "Ebooks": "電子書籍",
    "Books are a man's best friend": "本は人間の最高の友です",
    "Exercises": "エクササイズ",
    "Learn": "学ぶ",
    "Budgeting": "家計管理",
    "Banking": "銀行取引",
    "Credit History": "信用履歴",
    "Debt Reduction": "債務削減",
    "Saving": "貯蓄",
    "Tax Filing": "確定申告",
    "min": "分",
    "sessions": "セッション",
    "Thank You!": "ありがとうございます！",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "入力内容が正常に保存されました。回答はいつでも履歴セクションで確認できます。",
    "Got it": "了解"
  },
  "ko": {
    "Resources": "리소스",
    "Tips": "팁",
    "Get control of your life": "삶을 통제하십시오",
    "Quotes": "명언",
    "One day at a time": "하루에 하나씩",
    "Ebooks": "전자책",
    "Books are a man's best friend": "책은 사람의 가장 친한 친구입니다",
    "Exercises": "운동",
    "Learn": "배우기",
    "Budgeting": "예산 편성",
    "Banking": "금융",
    "Credit History": "신용 기록",
    "Debt Reduction": "부채 감축",
    "Saving": "저축",
    "Tax Filing": "세금 신고",
    "min": "분",
    "sessions": "세션",
    "Thank You!": "감사합니다!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "항목이 성공적으로 저장되었습니다. 내역 섹션에서 언제든지 답변을 다시 확인할 수 있습니다.",
    "Got it": "확인"
  },
  "id": {
    "Resources": "Sumber Daya",
    "Tips": "Tips",
    "Get control of your life": "Kendalikan hidup Anda",
    "Quotes": "Kutipan",
    "One day at a time": "Satu hari demi satu hari",
    "Ebooks": "Ebook",
    "Books are a man's best friend": "Buku adalah sahabat terbaik manusia",
    "Exercises": "Latihan",
    "Learn": "Belajar",
    "Budgeting": "Penyusunan Anggaran",
    "Banking": "Perbankan",
    "Credit History": "Riwayat Kredit",
    "Debt Reduction": "Pengurangan Hutang",
    "Saving": "Menabung",
    "Tax Filing": "Pelaporan Pajak",
    "min": "mnt",
    "sessions": "sesi",
    "Thank You!": "Terima Kasih!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Entri Anda telah berhasil disimpan. Anda dapat melihat kembali tanggapan Anda kapan saja di bagian Riwayat.",
    "Got it": "Mengerti"
  },
  "ms": {
    "Resources": "Sumber",
    "Tips": "Petua",
    "Get control of your life": "Kawal hidup anda",
    "Quotes": "Petikan",
    "One day at a time": "Satu hari demi satu hari",
    "Ebooks": "E-buku",
    "Books are a man's best friend": "Buku adalah sahabat terbaik manusia",
    "Exercises": "Senaman",
    "Learn": "Belajar",
    "Budgeting": "Bajet",
    "Banking": "Perbankan",
    "Credit History": "Sejarah Kredit",
    "Debt Reduction": "Pengurangan Hutang",
    "Saving": "Simpanan",
    "Tax Filing": "Pemfailan Cukai",
    "min": "min",
    "sessions": "sesi",
    "Thank You!": "Terima Kasih!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Entri anda telah berjaya disimpan. Anda boleh menyemak semula maklum balas anda pada bila-bila masa di bahagian Sejarah.",
    "Got it": "Faham"
  },
  "th": {
    "Resources": "แหล่งข้อมูล",
    "Tips": "เคล็ดลับ",
    "Get control of your life": "ควบคุมชีวิตของคุณ",
    "Quotes": "คำคม",
    "One day at a time": "ทีละวัน",
    "Ebooks": "อีบุ๊ก",
    "Books are a man's best friend": "หนังสือคือเพื่อนที่ดีที่สุด",
    "Exercises": "แบบฝึกหัด",
    "Learn": "เรียนรู้",
    "Budgeting": "การทำงบประมาณ",
    "Banking": "การธนาคาร",
    "Credit History": "ประวัติเครดิต",
    "Debt Reduction": "การลดหนี้",
    "Saving": "การออม",
    "Tax Filing": "การยื่นภาษี",
    "min": "นาที",
    "sessions": "เซสชัน",
    "Thank You!": "ขอบคุณ!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "บันทึกข้อมูลของคุณเรียบร้อยแล้ว คุณสามารถกลับมาดูการตอบกลับของคุณได้ทุกเมื่อในส่วนประวัติ",
    "Got it": "ตกลง"
  },
  "sw": {
    "Resources": "Rasilimali",
    "Tips": "Vidokezo",
    "Get control of your life": "Chukua udhibiti wa maisha yako",
    "Quotes": "Nukuu",
    "One day at a time": "Siku moja kwa wakati",
    "Ebooks": "Vitabu vya mtandao",
    "Books are a man's best friend": "Vitabu ni rafiki bora wa mwanadamu",
    "Exercises": "Mazoezi",
    "Learn": "Jifunze",
    "Budgeting": "Bajeti",
    "Banking": "Ubenki",
    "Credit History": "Historia ya Mikopo",
    "Debt Reduction": "Kupunguza Madeni",
    "Saving": "Akiba",
    "Tax Filing": "Uwasilishaji wa Kodi",
    "min": "dak",
    "sessions": "vikao",
    "Thank You!": "Asante!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Ingizo lako limehifadhiwa kwa mafanikio. Unaweza kupitia majibu yako wakati wowote katika sehemu ya Historia.",
    "Got it": "Nimeelewa"
  },
  "ro": {
    "Resources": "Resurse",
    "Tips": "Sfaturi",
    "Get control of your life": "Preia controlul asupra vieții tale",
    "Quotes": "Citate",
    "One day at a time": "Câte o zi pe rând",
    "Ebooks": "Ebook-uri",
    "Books are a man's best friend": "Cărțile sunt cei mai buni prieteni ai omului",
    "Exercises": "Exerciții",
    "Learn": "Învață",
    "Budgeting": "Bugetare",
    "Banking": "Activitate Bancară",
    "Credit History": "Istoricul Creditului",
    "Debt Reduction": "Reducerea Datoriilor",
    "Saving": "Economisire",
    "Tax Filing": "Depunerea Taxelor",
    "min": "min",
    "sessions": "sesiuni",
    "Thank You!": "Mulțumim!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Intrarea dvs. a fost salvată cu succes. Puteți reveni la răspunsurile dvs. oricând în secțiunea Istoric.",
    "Got it": "Am înțeles"
  },
  "pl": {
    "Resources": "Zasoby",
    "Tips": "Wskazówki",
    "Get control of your life": "Przejmij kontrolę nad swoim życiem",
    "Quotes": "Cytaty",
    "One day at a time": "Dzień po dniu",
    "Ebooks": "E-booki",
    "Books are a man's best friend": "Książki są najlepszymi przyjaciółmi człowieka",
    "Exercises": "Ćwiczenia",
    "Learn": "Ucz się",
    "Budgeting": "Budżetowanie",
    "Banking": "Bankowość",
    "Credit History": "Historia Kredytowa",
    "Debt Reduction": "Redukcja Zadłużenia",
    "Saving": "Oszczędzanie",
    "Tax Filing": "Rozliczenie Podatkowe",
    "min": "min",
    "sessions": "sesje",
    "Thank You!": "Dziękujemy!",
    "Your entry has been saved successfully. You can revisit your responses anytime in the History section.": "Twój wpis został pomyślnie zapisany. Możesz przejrzeć swoje odpowiedzi w dowolnym momencie w sekcji Historia.",
    "Got it": "Rozumiem"
  }
};

for (const lang in translations) {
  if (!cache[lang]) cache[lang] = {};
  for (const text in translations[lang]) {
    cache[lang][text] = translations[lang][text];
  }
}

fs.writeFileSync(CACHE_FILE, JSON.stringify(cache, null, 2));
console.log("Successfully seeded manual translations for all remaining languages!");
